matrix:
  include:
    - os: linux
      env: NODE_VERSION=5.1

install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

before_script:
  - chmod +x ./scripts/build.js
  - npm install

script:
  - npm test

before_deploy:
  - npm run build:linux
  - npm run build:win32
  - npm run build:darwin
  - zip -r Chrome-win32-ia32.zip ./bin/Chrome-win32-ia32
  - zip -r Chrome-win32-x64.zip ./bin/Chrome-win32-x64
  - zip -r Chrome-linux-ia32.zip ./bin/Chrome-linux-ia32
  - zip -r Chrome-linux-x64.zip ./bin/Chrome-linux-x64
  - zip -r Chrome-darwin-x64.zip ./bin/Chrome-darwin-x64

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
    - build-essential
    - git
    - fakeroot
    - wine
    - zip

deploy:
  provider: releases
  api_key:
    secure: VYOfaGvn1q6ey31cWAL2qcbrfSrjR4cVIUCmGxEODUpXSY+jlYjfY3Tcpa0MJFrKxfUJDIwdOlBahD3+JermHDugefsuJYnAF2JfPhND6o5B79AuRbi/D73fMz4ZJ2PHgW+IYOtW6uhFSnZAUeOcOuojI3+OjR2LNX4b3WkLzoRUF9l6cXjr/Jhc8+08KmC8bmajSaJFzW1PhzYIa8/S3iDhafQBsd1v4h6LD8AYfH86ObZ6wAt5YnWSZWmt1Uo2Zezs5ClUokIxfk5/H49PlGOqB7/RcZr4AukO0ab+te3QYS5XZDS+iAiYWozyvLEPhsxUGT4T9NiC72yuoF0galmbiW3gljnpDkB8S7qNa6tyK3/UT8H1Ey/e5CKKLsxWJtDdZDskGrrhgcsIByy+IBw6o6LS75SqnU/h4uUJx/8kxmCQWSrhEfB2tkRTqPauuK5503tMhz21oLX1KYA5dW/DzGSTufQjiKoI7J9d4VaHhcV5yXaCAsNQsG9cJf7JQyWL7ED4sQYGMDjEZ/JfjJjiWSWUbVU9HuzNAHXPcqa6VouPfEk7CjaifMHFiNnOJcArR5983Q3YLb5gAxPCbOL9PxNUJm8Yvhk74DHtxKNIjQK0GyFejyLu/E7r7YJ768SPcnjqvpUc5ayOPpOmRHuYwPyzvLD5vXG7sSFxsXw=
  file:
    - Chrome-win32-ia32.zip
    - Chrome-win32-x64.zip
    - Chrome-linux-ia32.zip
    - Chrome-linux-x64.zip
    - Chrome-darwin-x64.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

after_deploy:
  - "echo 'Chrome Material Design deployed!'"
